### ISSUE TITLE
Few unclear points

### ISSUE THREAD

**Issue by rfourquet** [jakobnissen/hardware_introduction#3]
Few things which I don't really understand and might need reformulation:

- "And you must strive to do your computation when only reading in your file once" (I can't make sense of this)
- "to move a single integer of data" (what is an integer of data?)
- "Data from the stack can only be accessed from the end" : to be pedantic, it's rather that data can be added or removed only from the end, but access to non-end can be fine. But might not be worth to bother with this detail.
- "[the compiler needs to know for certain that:] The compiler can predict exactly when it needs to access the program so it can reach it by simply popping the stack" (I'm not sure what "compiler accesses the program" means)

Also, there is a `N - N\%4` somewhere, the `\` seems to be spurious

**Comment by jakobnissen** [comment]
Fixed - I think!
