### ISSUE TITLE
Missing data file

### ISSUE THREAD

**Issue by AndrewGibbs** [jakobnissen/hardware_introduction#4]
The Julia notebook loads the file "/Users/jakobnissen/Downloads/test.jgi.abundance.dat" in the second cell. Currently this causes an error for me as I do not have this file! Perhaps this file could be included and this line amended?

**Comment by jakobnissen** [comment]
Fixed by fe717cc. To run this yourself, you will need to specify 2 different of your own files, neither of which should be recently used, so it doesn't matter much. But still, good to fix.
