### ISSUE TITLE
A few suggestions 

### ISSUE THREAD

**Issue by digital-carver** [jakobnissen/hardware_introduction#7]
These are a few suggestions where I either don't know the solution, or felt they were too subjective to include in the PR, so I'll leave these here up to your judgment.

---

`"Size of $T: "` in Pluto unfortunately prints `Size of Main.var"workspace#3".AlignmentTest: ` which makes the output a bit hard to read. It would be nice if there was a way to avoid the `Main.var ...` prefix in the output. 

---
The text says 
> There is no register that can do 128-bit additions. 

followed in the next paragraph by 
> modern CPUs contain specialized 256-bit registers (or 128-bit in older CPUs, or 512-bit in the brand new ones)

I'm not sure of the exact phrasing to use (perhaps there is established terminology for the usual "non-specialized" registers that I don't know of), but maybe the first sentence could be changed to something like "Traditionally, registers on the CPU cannot do 128-bit additions."

---
 In the "SIMD needs a loop where loop order doesn't matter" section, the first code block doesn't use `print`, and instead uses Pluto's default output of the cell to show the value. Since the rest of the notebook shows output *below* the cell, it maybe unintuitive to non-Pluto users to look for the output *above* the cell in this one case. So perhaps change that to 
```
begin
    x = eps(1.0) * 0.4
    print(1.0 + (x + x) == (1.0 + x) + x)
end
```
or 
```
 begin
     x = eps(1.0) * 0.4
     (1.0 + (x + x) == (1.0 + x) + x) |> print
 end
```
(whichever seems more readable/easy-to-understand)

**Comment by jakobnissen** [comment]
Thanks for the suggestions! :heart:  I've implemented them all and updated the website. It should be live in a few minutes.
